$(function(){

    
    var header = 
	'<header id="header" class="header">'

	+'<div class="inner">'
	+	'<div class="log_wrap">'
	+		'<ul>'
	+			'<li>'
	+				'<span class="login_team">품질경영팀</span> <span class="login_user">박대희</span> 님'
	+			'</li>'
	+			'<li class="admin" data-layer="layer-t01">'
	+				'<a href="/Admin/Login.aspx">'
	+					'<img src="../image/renew/btn_admin_page.png" alt="마스터관리" />'
	+				'</a>'
	+			'</li>'
	+			'<li class="site">'
	+				'<a href="/SiteMap/Sitemap.aspx">'
	+					'<img src="../image/renew/btn_sitemap.png" alt="사이트맵" />'
	+				'</a>'
	+			'</li>'
	+		'</ul>'
	+	'</div>'
	+	'<div class="gnb_wrap clear_both">'
	+		'<h1 class="logo"><a href="#none"><img src="../image/renew/logo_header.png" alt="Q-tas"/></a></h1>'
	
	+		'<div class="nav_wrap">'
	+			'<ul class="clear_both">'		
	+				'<li class="item01">'
	+					'<a href="/Intro/Purpose.aspx">품질종합분석시스템</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="/Intro/Purpose.aspx">품질종합분석시스템목적</a></li>'
	+							'<li><a href="/Intro/Process.aspx">품질불량분석프로세스</a></li>'
	+							'<li><a href="/Intro/Function.aspx">시스템 주요 기능</a></li>'
	+							'<li><a href="/Intro/Way.aspx">시스템 사용방법</a></li>' 
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'
	+				'<li class="item02">'
	+					'<a href="/Return/UpgradeLst.aspx">통합품질정보</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="/Qinfo/ImproveList.aspx">품질개선진도관리현황</a></li>'
	+							'<li><a href="/Qinfo/FailList.aspx">실패사례Factory</a> </li>'
	+							'<li>'
	+								'<a href="/Qinfo/FaultList.aspx">품질정보</a>'
	+								'<!--'
	+								'<div>'
	+									'<ul>'
	+										'<li><a href="/Qinfo/FaultList.aspx?idx=1">- 입고품질정보</a></li>'
	+										'<li><a href="/Qinfo/FaultList.aspx?idx=2">- 출하품질정보</a></li>'
	+										'<li><a href="/Qinfo/FaultList.aspx?idx=3">- 필드품질정보</a></li>'
	+										'<li><a href="/Qinfo/FaultList.aspx?idx=4">- 신뢰성 시험 정보</a></li>'
	+										'<li><a href="/Qinfo/FaultList.aspx?idx=5">- 해외품질정보</a></li>'
	+									'</ul>'
	+								'</div>-->'
	+							'</li>'
	+							'<li><a href="/Return/SummaryLst.aspx">반환분석_개선과제 집계현황</a></li>'
	+							'<li><a href="/Return/UpgradeLst.aspx">반환분석_개선과제 등록</a></li>'
	+							'<li><a href="/Return/ProgressLst.aspx">반환분석_개선진도관리 현황</a></li>  '  
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'
	+				'<li class="item03">'
	+					'<a href="/Voc/UpgradeLst.aspx">Q-Report</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="/QReport/DailyQualityList.aspx">일일품질그물망 현황보고</a></li>'
	+							'<li><a href="/QReport/IssueList.aspx">품질개선과제 등록</a></li>'
	+							'<li>'
	+								'<a href="/QReport/List.aspx">일반보고</a>'
	+								'<!--'
	+								'<div>'
	+									'<ul>'
	+										'<li><a href="Javascript:PopupReplyWrite()">- 주간보고</a></li>'                    
	+									'</ul>'
	+								'</div>-->'
	+							'</li>'
	+							'<li><a href="/Voc/SummaryLst.aspx">VOC_집계현황</a></li>'
	+							'<li><a href="/Voc/UpgradeLst.aspx">VOC_개선과제 현황</a></li>'
	+							'<li><a href="/Voc/ProgressLst.aspx">VOC_개선 진도관리 현황</a></li>'
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'
	+				'<li class="item04">'
	+					'<a href="">품질지표</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="">종합지표</a></li>'
	+							'<li><a href="">Q-Anaysis</a></li>'
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'
	+				'<li class="item05">'
	+					'<a href="/Notice/List.aspx">공지사항</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="/Notice/List.aspx">일반공지</a></li>'
	+							'<li><a href="/Notice/ProductList.aspx">신제품/OEM DR현황</a></li>'
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'
	+				'<li class="item06">'
	+					'<a href="/Voc/UpgradeLst.aspx">자료실</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="/PDS/List.aspx?division=2">품질기획</a></li>'
	+							'<li><a href="/PDS/List.aspx?division=3">입고</a></li>'
	+							'<li><a href="/PDS/List.aspx?division=4">출하</a></li>'
	+							'<li><a href="/PDS/List.aspx?division=5">필드</a></li>'  
	+							'<li><a href="/PDS/List.aspx?division=6">신뢰성</a></li>' 
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'
	+				'<li class="item07">'
	+					'<a href="/QnA/List.aspx">Q&A</a>'
	+					'<div class="item_cont"><div>'
	+						'<ul>'
	+							'<li><a href="/QnA/List.aspx?division=2">전산시스템</a></li>'
	+							'<li><a href="/QnA/List.aspx?division=3">품질분야</a></li>'   
	+						'</ul>'
	+					'</div></div>'
	+				'</li>'		
	+			'</ul>'
	+		'</div>'
	+	'</div>'
	+'</div>'
	+'</header>';

    var footer = 
	'<footer id="footer" class="footer">'
	+	'<div class="inner">'
			
	+		'<div class="logo">'
	+			'<a href="#none"><img src="../image/renew/logo_footer.png" alt="Q-tas"/></a>'
	+		'</div>'

	+		'<div class="infos">'
	+			'<ul class="clear_both">'
	+				'<li>'
	+					'사업자번호 : 307-81-06054'
	+				'</li>'
	+				'<li>'
	+					'통신판매번호 : 제 2005-21호'
	+				'</li>'
	+				'<li>'
	+					'주소 : 충청남도 공주시 유구읍 유구마곡사로 136-23 '
	+				'</li>'
	+				'<li>'
	+					'대표이사 : 김동현'
	+				'</li>'
	+			'</ul>'
	+			'<div class="copyright">Copyright ⓒ Woongjin Coway Co.Ltd, All Reserved.</div>'
	+		'</div>'

	+	'</div>'
	+'</footer>';

	
    $("#header").html(header);
    $("#header #header").unwrap();

    $("#footer").html(footer);
    $("#footer #footer").unwrap();
	
});